# Generated by Django 5.0 on 2024-01-31 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='file/')),
                ('version', models.FloatField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprac.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Review', 'Review'), ('Working', 'Working'), ('Awaiting_release', 'Awaiting Release'), ('Waiting_qa', 'Waiting Qa')], default='Open')),
                ('project', models.ManyToManyField(to='apprac.project')),
                ('assignee', models.ManyToManyField(to='apprac.user')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team_member',
            field=models.ManyToManyField(to='apprac.user', verbose_name='Team Member'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField()),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('qa', 'Qa'), ('developer', 'Developer')], default='developer')),
                ('display_pic', models.ImageField(upload_to='image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apprac.user', verbose_name='User Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprac.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprac.task')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprac.user')),
            ],
        ),
    ]
