# Generated by Django 5.0 on 2024-01-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprac', '0002_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
