# Generated by Django 5.0 on 2024-02-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprac', '0003_profileproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprac.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprac.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprac.task')),
            ],
        ),
    ]
