# Generated by Django 5.0 on 2024-01-31 16:17

import apprac.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprac', '0006_remove_task_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='version',
            field=apprac.models.VersionField(),
        ),
    ]
